### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FarhanRehman** [chorobikmichal/HQ-Trivia-BOT#8]
![image](https://user-images.githubusercontent.com/37966672/39952881-3608fd02-556e-11e8-8504-dbbb3e48cf03.png)

How to I fix this

**Comment by savageduckerino** [comment]
type pip install pyQt5

**Comment by vishu002** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/52373276/60395481-d7ff4d80-9b51-11e9-826c-c144983e6c6d.png)
how to fix this pls you are understanding in this pls guide me ok
